### ISSUE TITLE
Internal Server Error when you want to place a Head

### ISSUE THREAD

**Issue by HighTec90** [Wertzui123/CB-Heads#10]
You get an Internal Server Error when you wanna Place a Head with the new Version 1.14.60.

<Server thread/Critical> RuntimeException: "Tag with name "Geomet
ryName" not found and no valid default value given" (EXCEPTION) in "vendor
/pocketmine/nbt/src/tag/CompoundTag" at line 193

**Comment by Wertzui123** [comment]
Thanks for reporting this issue. I will look into it, when I have time for it.

**Comment by HimmelKreis4865** [comment]
Hello, this issue is caused by Altay. 

If you're using Altay, you can't use CB-Heads. 

If you're not, then there's another mistake.

**Comment by HighTec90** [comment]
Update for this Issue:
Himmelkreis was right. It is was an Altay specific Issue.
It is fixed now, now i get a fully Skin instead of only the Head :-D

**Comment by Wertzui123** [comment]
So the problem is solved?

**Comment by HighTec90** [comment]
yep its solved
