### ISSUE TITLE
Falsches Datum

### ISSUE THREAD

**Issue by MonoAdrian23** [Wertzui123/CB-Heads#12]
Bei jedem Monatswechsel, kommt du kannst erst wieder am bsp. 31.05.2020 einen Kopf machen.
Heute ist der 2.6.2020
CB Heads Latest 
Pocketmine 3.12.3

**Comment by Wertzui123** [comment]
This issue is invalid due to the code rewrite in version 3.0.
Please reopen it if the problem still exists in version 3.0.
