### ISSUE TITLE
Datum entfernen und durch einen normlen Cooldown ersetzen

### ISSUE THREAD

**Issue by supercrafter333** [Wertzui123/CB-Heads#13]
Hi,
du könntest doch einfach das datum weglassen, und wie bei deinem Rewards Plugin, einfach die zeit anzeigenlassen, wie lange es noch dauert, bis man sich wieder einen Kopf holen kann. :)

MFG
supercrafter333

**Comment by Wertzui123** [comment]
Das ist bereits in Planung für die nächste Version.

**Comment by Wertzui123** [comment]
Dieses Feature wurde in Version 3.0 implementiert.
