### ISSUE TITLE
Köpf Entitys als NPCs

### ISSUE THREAD

**Issue by supercrafti** [Wertzui123/CB-Heads#14]
Die Kopf Enitys stehen jetzt als Spielergroße Steve NPCs da. Bitte aktualisiere das Plugin gemäß der API Änderungen an Pocketmine 3.13.0.

**Comment by Wertzui123** [comment]
Hallo,

meines Wissens nach ist das ein Client-Side Problem. Deaktivieren die "Trusted Skins" Einstellung und probiere es erneut.

**Comment by supercrafti** [comment]
> Hallo,
> 
> meines Wissens nach ist das ein Client-Side Problem. Deaktivieren die "Trusted Skins" Einstellung und probiere es erneut.

Wo deaktiviere ich die?

**Comment by Wertzui123** [comment]
Das weiß ich nicht, da ich noch die 1.14.6 benutze.

**Comment by supercrafti** [comment]
Und wo kann man sie da deaktivieren? 😇

**Comment by Wertzui123** [comment]
Das weiß ich immernoch nicht. Ich empfehle dir einfach alle Einstellungen zu durchsuchen.

**Comment by supercrafti** [comment]
Pocketmine oder im Spiel selbst?

**Comment by Wertzui123** [comment]
Im Spiel selbst.

**Comment by HimmelKreis4865** [comment]
Falls du die 1.16 benutzt, solltest du es unter `Einstellungen > Profil > Nicht Vertrauenswürdige Skins deaktiveren` abschalten können. (Könnte auch anders heißen, ich weiß es nicht mehr auswendig.)

**Comment by MonoAdrian23** [comment]
Hat geholfen, aber dafür fliegen Köpfe jetzt

**Comment by Wertzui123** [comment]
Kannst du mir bitte ein Bild davon senden?

**Comment by MonoAdrian23** [comment]
Hab es dc geschickt

**Comment by Wertzui123** [comment]
Anscheinend ist das Problem mit der Minecraft Bedrock Version 1.16.1 behoben. Falls nicht, kontaktiere mich bitte erneut. Ansonsten werde ich diese Issue in den nächsten Tagen schließen.

**Comment by supercrafti** [comment]
> Anscheinend ist das Problem mit dem Minecraft Bedrock Version 1.16.1 behoben. Falls nicht, kontaktiere mich bitte wieder. Ansonsten werde ich diese Ausgabe in den nächsten Tagen schließen.

Das problem ist behoben, PMMP hat es gefixt. Es lag aber an der einstellung, danke.
