### ISSUE TITLE
Cooldown umgänglich [Sehr wichtig!]

### ISSUE THREAD

**Issue by EndermanLetsPlay** [Wertzui123/CB-Heads#16]
Hi! Erst einmal vielen Dank für das Bereitstellen dieses schönen Plugins.

Leider ist mir aufgefallen, dass man den Cooldown umgehen kann, wenn man das Datums-Format zu beispielsweise "d.m.Y H:i" ändert.

Da dieses Problem zu großen Konflikten führen kann, bitte ich um schnelle Behebung.

Vielen Dank im Voraus.

**Comment by Wertzui123** [comment]
This issue is invalid due to the code rewrite in version 3.0.
Please reopen it if the problem still exists in version 3.0.
