### ISSUE TITLE
Ich kann den Kopf nicht abbauen

### ISSUE THREAD

**Issue by debugkokichi** [Wertzui123/CB-Heads#17]
Der Kopf lässt sich nicht abbauen egal was man Versucht! Lava/Abbauen/Schlagen usw geht nicht!

**Comment by Wertzui123** [comment]
Kannst du an der Stelle Blöcke zerstören?

**Comment by tim51159** [comment]
Ja kann man (aber) man kann nichts platzieren [Nur drunter und drüber rechts und Links kann man nichts abbauen]

**Comment by Wertzui123** [comment]
Ist PVE und PVP an?

**Comment by tim51159** [comment]
Jap ist es

**Comment by Wertzui123** [comment]
This issue is invalid due to the code rewrite in version 3.0.
Please reopen it if the problem still exists in version 3.0.
