### ISSUE TITLE
Admin-Only Heads

### ISSUE THREAD

**Issue by Platz1** [Wertzui123/CB-Heads#2]
Könntest du bitte eine Funktion einbauen, dass man nur Leute mit einer bestimmten Permission sich die Köpfe von bestimmten Spielern, die man in der Config angibt, geben lassen kann?

Dies wäre praktisch, um den Wert der Teammidglied-Köpfe zu wahren.

**Comment by Wertzui123** [comment]
Hm, dass ist ne super idee. Ich werde versuchen sie umzusetzen. Für mehr mit mir chatten kannst du gerne in meinen Discord kommen -> https://discord.gg/XXkZGsP

**Comment by Wertzui123** [comment]
Ich habe mal damit angefangen... Sollte bald fertig sein

**Comment by Wertzui123** [comment]
Ich habe das Feature unter dem Namen "blacklist" eingeführt. Du kannst es dir mal angucken :wink:

**Comment by Platz1** [comment]
thx
