### ISSUE TITLE
SUGGESTION

### ISSUE THREAD

**Issue by MadooxMc** [Wertzui123/CB-Heads#20]
When player was kill by other player, this head drop

**Comment by MadooxMc** [comment]
It was suggestion

**Comment by Wertzui123** [comment]
Do you mean players should drop their heads when killed (if you enable this feature in the config)?

**Comment by MadooxMc** [comment]
Yes is that !!!! If you do that, This plugin would be really useful for pvp servers and players would be proud to get the heads of other players they would kill

**Comment by Wertzui123** [comment]
Yea, I think so too.

**Comment by Wertzui123** [comment]
This feature was added in a99f0bba978374b566ada644cf201df27790cafd.
