### ISSUE TITLE
Suggestion: players shouldn't get their head when killing themselves

### ISSUE THREAD

**Issue by SPMP2** [Wertzui123/CB-Heads#22]
Please can you fix: Head drop by me example:
If i kill myself / if players kill himself head droped but it’s better if player kill himself he doesn’t get this head

**Comment by Wertzui123** [comment]
That's right, thanks for pointing that out.
I think this is more of a suggestion than a bug report though, so I will rename the issue.

**Comment by Wertzui123** [comment]
What do you mean?
I will probably implement this tomorrow.

**Comment by SPMP2** [comment]
Okok thank you very mutch 🙏 i am selling the head of player in my server but players can auto kill and selling their head 😭

**Comment by Wertzui123** [comment]
Yea, that doesn't make much sense.

**Comment by SPMP2** [comment]
Thank’s 😊
