### ISSUE TITLE
Add config option to reenable xp orb attraction by heads

### ISSUE THREAD

**Issue by xodamcm** [Wertzui123/CB-Heads#24]
On config:
#Head can attract xp orbs: True/False
- true

**Comment by Wertzui123** [comment]
When would you ever want heads to attract XP orbs anyway?

**Comment by xodamcm** [comment]
#Attract XP Orbs
head-attract-xp-orbs: 
- true 
#If is true, heads to attract xp orbs
#If is false, heads not attract xp orbs

**Comment by Wertzui123** [comment]
I know, but that's not the answer to my question.

**Comment by xodamcm** [comment]
Ok… so i don’t understand your question, i need you the xp orbs attract feature like other version..

**Comment by Wertzui123** [comment]
Ok, but why?

**Comment by xodamcm** [comment]
Because with your plugin, when you put a head of player not far away a BurgerSpawner, that desactivate the spawn of mobs, and if you put a lava to kill mobs and put head to stock xp, you can make auto farm and when you kill the head you earn the xp

**Comment by Wertzui123** [comment]
Ok, but shouldn't you just use another plugin just for this? Implementing a bug only for the sake of abusing it is kind of weird.

**Comment by xodamcm** [comment]
Ok
