### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by NdaruAjaa** [Wertzui123/CB-Heads#25]
PocketMine-MP version: 5.2.0 [Protocol 589]
Git commit: e6de9a70a211e1c2f4472dc2c4a0155ba0ffa5b2
PHP version: 8.1.20
OS: Linux, linux

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: CB-Heads

Error: Call to undefined method pocketmine\block\MobHead::setSkullType()
File: plugins/CB-Heads/src/Wertzui123/CBHeads/entities/Head
Line: 53
Type: Error
Backtrace:
#0 pmsrc/src/player/Player(1860): Wertzui123\CBHeads\entities\Head->attack(object pocketmine\event\entity\EntityDamageByEntityEvent#110973)
#1 pmsrc/src/network/mcpe/handler/InGamePacketHandler(555): pocketmine\player\Player->attackEntity(object Wertzui123\CBHeads\entities\Head#120821)
#2 pmsrc/src/network/mcpe/handler/InGamePacketHandler(342): pocketmine\network\mcpe\handler\InGamePacketHandler->handleUseItemOnEntityTransaction(object pocketmine\network\mcpe\protocol\types\inventory\UseItemOnEntityTransactionData#107597)
#3 pmsrc/vendor/pocketmine/bedrock-protocol/src/InventoryTransactionPacket(94): pocketmine\network\mcpe\handler\InGamePacketHandler->handleInventoryTransaction(object pocketmine\network\mcpe\protocol\InventoryTransactionPacket#108766)
#4 pmsrc/src/network/mcpe/NetworkSession(437): pocketmine\network\mcpe\protocol\InventoryTransactionPacket->handle(object pocketmine\network\mcpe\handler\InGamePacketHandler#144618)
#5 pmsrc/src/network/mcpe/NetworkSession(381): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\InventoryTransactionPacket#108766, string[32] .........&YC>.g@z..C............)
#6 pmsrc/src/network/mcpe/raklib/RakLibInterface(217): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[32] c.a.a.b.9.f.aF...j..v....8.:3 ..)
#7 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(40): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(int 2, string[41] .+.C.iP.8i.fZ0e....".<t.....n...TM...c...)
#8 pmsrc/src/network/mcpe/raklib/RakLibInterface(109): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#191594)
#9 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(120): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
#10 pmsrc/src/TimeTrackingSleeperHandler(58): pocketmine\snooze\SleeperHandler->processNotifications()
#11 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(79): pocketmine\TimeTrackingSleeperHandler->processNotifications()
#12 pmsrc/src/Server(1674): pocketmine\snooze\SleeperHandler->sleepUntil(float 1688914591.9361)
#13 pmsrc/src/Server(1063): pocketmine\Server->tickProcessor()
#14 pmsrc/src/PocketMine(334): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#6, object pocketmine\utils\MainLogger#3, string[16] /home/container/, string[24] /home/container/plugins/)
#15 pmsrc/src/PocketMine(357): pocketmine\server()
#16 pmsrc(11): require(string[60] phar:///home/container/PocketMine-MP.phar/src/PocketMine.php)

**Comment by Wertzui123** [comment]
Thank you!
