### ISSUE TITLE
Can't "kill" the Heads

### ISSUE THREAD

**Issue by SuperStulle007** [Wertzui123/CB-Heads#5]
The Plugin is great, but i have a bug. Everytime i place a head i can't destroy or kill the Head. So the head won't drop. There is no way to remove the head (lava, World Edit, water, TnT...). It doesn't work with op or with the cb-heads.kill permission. 

Software: PmmP: 3.8.1

**Comment by Wertzui123** [comment]
Hm, you can build where you try it? Are you using the latestv CB-Heads version?

**Comment by SuperStulle007** [comment]
Yes im using the latest version and i can build theme wherever i want. I only can't kill the head...

**Comment by Wertzui123** [comment]
Hm, please send me IP and Port of your server. Best thing you use discord, I'm Wertzui123#1317

**Comment by SuperStulle007** [comment]
The Plugin "AntiAutoBreak" blocked the ability, to kill the heads

**Comment by Wertzui123** [comment]
Ok. I warned the users in the readme a minute ago.
