### ISSUE TITLE
Kopf?

### ISSUE THREAD

**Issue by Baducai** [Wertzui123/CB-Heads#6]
Man kann den Kopf nicht mit einem schlag entfernen.

**Comment by Wertzui123** [comment]
Dann kannst du da nicht bauen.

**Comment by Baducai** [comment]
Aber ich habe OP auf dem Server

**Comment by Wertzui123** [comment]
Adtesse?

**Comment by Wertzui123** [comment]
Welche CB-Heads Version?

**Comment by Baducai** [comment]
Wieso funktioniert das auf Plots nicht aber in anderen Welten schon?

**Comment by Wertzui123** [comment]
Es sollte dort gehen wo du abbauen kannst. Und Check ob PvP auf dem Plot deaktiviert ist!

**Comment by Baducai** [comment]
funktioniert immer noch nicht

**Comment by Wertzui123** [comment]
Check ob PvE auf dem Plot, auf dem Server oder in der Welt deaktiviert ist.
