### ISSUE TITLE
Unlimited Heads!

### ISSUE THREAD

**Issue by MonoAdrian23** [Wertzui123/CB-Heads#8]
Hello Wertzui
Pocketmine 3.11.3
Latest Version Cb-Heads
Players can create Unlimited Heads!
Time 1440 
Correct Permissions set.

**Comment by Wertzui123** [comment]
So, there's no waiting period?

**Comment by MonoAdrian23** [comment]
No, in config is 1440 but all players with Permissions can give Unlimited Heads.
1440 Minutes is written in Config.
Thank you for Youre help

**Comment by Wertzui123** [comment]
So you can claim the heads without waiting?

**Comment by MonoAdrian23** [comment]
Yes. There's no waiting period for all

**Comment by Wertzui123** [comment]
I will look into it, thanks for reporting

**Comment by MonoAdrian23** [comment]
Thank you very much.
Youre Head plugin is the best.

**Comment by Killian92** [comment]
Kannst du mir erklären wie ich das behebe?

**Comment by Wertzui123** [comment]
An issue labed als 'Bug' is a bug - I don't know how to fix it yet, so I cannot tell you.

**Comment by Killian92** [comment]
Hab den Bug gefunden
Als lag am Scorehud
Mein Server erkannte eine falsche Zeitzone und habe es gefixt bekommen.
Danke dir!

**Comment by Wertzui123** [comment]
But the bug is still a thing for you? @MonoAdrian23

**Comment by Wertzui123** [comment]
Has the problem been solved?

**Comment by MonoAdrian23** [comment]
Yes thanks
